sudo: required

language: generic

dist: trusty

env:
  global:
    - BUILDER=catkin
    - NO_SUDO=true
    - NOT_TEST_INSTALL=false
    - USE_TRAVIS=true
    - USE_DEB=true
    - ROS_PARALLEL_JOBS="-j8"
    - ROSWS=wstool
    - ROSDEP_ADDITIONAL_OPTIONS="-q -n --ignore-src"
  matrix:
    - ROS_DISTRO=indigo

script:
  # build & test ROS packages
  - source .travis/travis.sh
  # build doc
  - cd $TRAVIS_BUILD_DIR/doc
  - unset PYTHONPATH  # cleanup for virtualenv
  - source setup.sh
  - make html

cache: ccache

notifications:
  email:
    on_success: always
    on_failure: always
  slack: jsk-robotics:Av7tc8wj3IWkLYvlTzHE7x2g
